services:
  mysql:
    image: mysql:8.0-oracle  # 官方原生支持ARM64的镜像
    platform: linux/arm64/v8  # 显式指定ARM64架构
    container_name: xxl-job-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123  # 生产环境请改为复杂密码
      MYSQL_DATABASE: xxl_job
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'  # 建议分配2核CPU
          memory: 2G  # 建议分配2GB内存

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.0.0  # 当前仅支持x86的镜像
    platform: linux/amd64  # 关键配置：强制通过Rosetta转译运行
    container_name: xxl-job-admin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useSSL=false&allowPublicKeyRetrieval=true
        --spring.datasource.username=root
        --spring.datasource.password=root123
        --xxl.job.accessToken=123456   
    volumes:
      - ./logs:/data/applogs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'  # 转译需要更多CPU资源
          memory: 4G  # 建议分配4GB内存

# 共用网络配置（Docker Compose V2+会自动创建，无需显式声明）